const express = require('express')
const errors = require('./network/errors')
const route = express.Router()
const cors = require('cors')
const login = require('./api/user/login')
const welcome = require('./api/welcome')
const register = require('./api/user/register')
const listUsers = require('./api/user/listUsers')
const createBank = require('./api/bank/createBank')
const reset = require('./api/user/reset')
const deleteuser = require('./api/user/deleteuser')
const updateuser = require('./api/user/update')
const getUser = require('./api/user/getUser')
const getTickets = require('./api/tickets/getTickets')
const getTicketDate = require('./api/tickets/getTicketDate')

const quiniela = require('./api/quiniela/quiniela')
const deposits = require('./api/deposits/deposits')
const deposit = require('./api/deposits/deposit')
const premios = require('./api/premios/premios')

const withdraws = require('./api/withdraws/withdraws')
const withdraw = require('./api/withdraws/withdraw')
const report = require('./api/report/report')
const reports = require('./api/report/reports')

const methods = require('./api/methods/methods')
const tickets = require('./api/tickets/tickets')
const reportes = require('./api/reportes/reportes')
const animals = require('./api/animals/animals')
const scripts = require('./api/scripts/scripts')
const config = require('./api/config/config')
const secrettoken = require('./api/secrettoken/secrettoken')
const transaction = require('./api/transaction/transaction')
const blockUser = require('./api/blockUser/blockUser')
const prepaid = require('./api/prepaid/prepaid')
const reportUsers = require('./api/reportUsers/reportUsers')
const pagoQuiniela = require('./api/pagoQuiniela/pagoQuiniela')
const transfer = require('./api/transfer/transfer')
const cron = require('./api/cron')
const router = (app) => {

    app.use(cors())
    app.use('/api/v1', route)
    route.use('/', welcome)
    route.use('/cron', cron)
    route.use('/scripts', scripts)
    route.use('/login', login)
    route.use('/animals', animals)
    route.use('/secrettoken', secrettoken)
    route.use('/transaction', transaction)
    route.use('/blockUser', blockUser)
    route.use('/prepaid', prepaid)
    route.use('/premios', premios)
    route.use('/transfer', transfer)
    route.use('/getTicketDate', getTicketDate)

    route.use('/register', register)
    route.use('/tickets', tickets)
    route.use('/gettickets', getTickets)
    route.use('/quiniela', quiniela)
    route.use('/deposits', deposits)
    route.use('/deposit', deposit)
    route.use('/withdraws', withdraws)
    route.use('/withdraw', withdraw)
    route.use('/pagoQuiniela', pagoQuiniela)

    route.use('/reportes', reportes)
    route.use('/report', report)
    route.use('/reports', reports)
    route.use('/reportUsers', reportUsers)
    route.use('/config', config)


    route.use('/user', getUser)
    route.use('/users', listUsers)
    route.use('/createBank', createBank)
    route.use('/reset', reset)
    route.use('/admin/deleteuser', deleteuser)
    route.use('/admin/updateuser', updateuser)

    route.use('/admin/methods', methods)
    route.use(errors)
}

module.exports = router